// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRONevBLl9iDcVkJsEuMwBlIc-htnqHog',
    appId: '1:417369954731:web:9c825e6eab2b9861e89aee',
    messagingSenderId: '417369954731',
    projectId: 'doomchain-10d3c',
    authDomain: 'doomchain-10d3c.firebaseapp.com',
    storageBucket: 'doomchain-10d3c.appspot.com',
    measurementId: 'G-487QZMKMTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMEhSEe9PjeyOdVP6UgXYGUzCMv0l7syI',
    appId: '1:417369954731:android:ac2c830b4fe136f8e89aee',
    messagingSenderId: '417369954731',
    projectId: 'doomchain-10d3c',
    storageBucket: 'doomchain-10d3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVRF-P6kMp2NPYA0VVLEAUMDz10ub2moA',
    appId: '1:417369954731:ios:5a15b284a6ff1ab2e89aee',
    messagingSenderId: '417369954731',
    projectId: 'doomchain-10d3c',
    storageBucket: 'doomchain-10d3c.appspot.com',
    iosClientId: '417369954731-s96fuahocb119u17ne6jnulcttl24krn.apps.googleusercontent.com',
    iosBundleId: 'com.example.doomChain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVRF-P6kMp2NPYA0VVLEAUMDz10ub2moA',
    appId: '1:417369954731:ios:5a15b284a6ff1ab2e89aee',
    messagingSenderId: '417369954731',
    projectId: 'doomchain-10d3c',
    storageBucket: 'doomchain-10d3c.appspot.com',
    iosClientId: '417369954731-s96fuahocb119u17ne6jnulcttl24krn.apps.googleusercontent.com',
    iosBundleId: 'com.example.doomChain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRONevBLl9iDcVkJsEuMwBlIc-htnqHog',
    appId: '1:417369954731:web:16d79e2dcbf51ddee89aee',
    messagingSenderId: '417369954731',
    projectId: 'doomchain-10d3c',
    authDomain: 'doomchain-10d3c.firebaseapp.com',
    storageBucket: 'doomchain-10d3c.appspot.com',
    measurementId: 'G-W90RJT65EW',
  );
}
